"""
Generates data.json for the pipeline health dashboard — SAMPLE/DEMO version.

Matches the real serving-db schema (verified 2026-09-26):
  pipeline_health      — one row per run
  transaction_summary  — one row per run
  flagged_transactions — one row per flagged transaction (raw detail)
"""
import json
import random
from datetime import datetime, timedelta

random.seed(7)

N_RUNS = 30
today = datetime(2026, 9, 26, 12, 0, 0)
run_timestamps = [(today - timedelta(days=N_RUNS - 1 - i)) for i in range(N_RUNS)]

pipeline_health = []
transaction_summary = []
recent_flagged = []

merchants = ["electronics", "groceries", "apparel", "travel", "dining", "digital_goods"]
payment_methods = ["credit_card", "debit_card", "upi", "wallet", "netbanking"]
locations = ["Mumbai", "Delhi", "Bengaluru", "Chennai", "Hyderabad", "Pune", "Kolkata"]

for i, ts in enumerate(run_timestamps):
    raw = int(500 * (1 + random.uniform(-0.05, 0.08)) + i * 2)
    null_amount = random.randint(2, 15)
    null_location = random.randint(2, 15)
    bad_payment = random.randint(1, 12)
    duplicate = random.randint(1, 8)
    dropped = null_amount + null_location + bad_payment + duplicate
    clean = raw - dropped

    pipeline_health.append({
        "run_timestamp": ts.isoformat(),
        "stage": "bronze_to_silver",
        "raw_row_count": raw,
        "clean_row_count": clean,
        "rows_dropped": dropped,
        "null_amount_count": null_amount,
        "null_location_count": null_location,
        "bad_payment_method_count": bad_payment,
        "duplicate_count": duplicate,
        "null_rate_pct": round((null_amount + null_location) / raw * 100, 2),
        "duplicate_rate_pct": round(duplicate / raw * 100, 2),
    })

    total = clean
    outlier = random.randint(0, max(1, int(total * 0.03)))
    velocity = random.randint(0, max(1, int(total * 0.015)))
    flagged = outlier + velocity
    transaction_summary.append({
        "run_timestamp": (ts + timedelta(minutes=6)).isoformat(),
        "total_transactions": total,
        "flagged_transactions": flagged,
        "flagged_rate_pct": round(flagged / total * 100, 2),
        "amount_outlier_count": outlier,
        "high_velocity_count": velocity,
        "total_transaction_value": round(total * random.uniform(1800, 2600), 2),
        "average_transaction_value": round(random.uniform(1800, 2600), 2),
        "note": "auto-generated by pipeline",
    })

# a handful of recent flagged transaction detail rows
for i in range(20):
    is_outlier = random.random() > 0.4
    recent_flagged.append({
        "transaction_id": f"txn_{100000 + i}",
        "user_id": f"user_{random.randint(1000, 9999)}",
        "amount": round(random.uniform(500, 45000), 2),
        "currency": "INR",
        "location": random.choice(locations),
        "merchant_category": random.choice(merchants),
        "payment_method": random.choice(payment_methods),
        "timestamp": (today - timedelta(hours=i * 3)).isoformat(),
        "amount_zscore": round(random.uniform(2.0, 5.5), 2),
        "flag_amount_outlier": is_outlier,
        "flag_high_velocity": not is_outlier or random.random() > 0.7,
    })

now = datetime(2026, 9, 26)
data = {
    "generated_at": now.isoformat(),
    "generated_date": now.date().isoformat(),
    "pipeline_health": pipeline_health,
    "transaction_summary": transaction_summary,
    "recent_flagged": recent_flagged,
}

with open("data.json", "w") as f:
    json.dump(data, f, indent=2)

print(f"Wrote data.json with {len(pipeline_health)} pipeline_health rows, "
      f"{len(transaction_summary)} transaction_summary rows, "
      f"{len(recent_flagged)} recent flagged transactions.")
